void test_initialise_multiplicities_of_allele_nodes_wrt_both_alleles();
void test_calc_log_likelihood_of_genotype_with_complex_alleles1();
void test_calc_log_likelihood_of_genotype_with_complex_alleles2();
