IDIR1 =/homes/zi/dev/hg/marzam/marzam-harmonised-populations/include
IDIR2 =/homes/zi/dev/hg/CUnit/CUnit-2.1-0/CUnit/Headers

CC = gcc
CFLAGS = -Wall -I$(IDIR1) -I$(IDIR2)
DEBUG = -g
LDFLAGS =
OPT = -O0


