
void test_read_sequence_from_fasta();
void test_read_sequence_from_fasta_when_file_has_long_and_bad_reads();
void test_read_sequence_from_fastq();
void test_read_sequence_from_fastq_with_bad_reads_and_long_reads();
