void test_load_two_people_in_same_populations_and_print_separately_their_supernodes();
void test_take_three_people_each_with_one_read_and_find_variants();
void test_take_two_people_sharing_an_alu_and_find_supernodes();
void test_loading_simple_fasta_and_getting_chromosome_intersections();
