void test_is_supernode_end();
void test_getting_stats_of_how_many_indivduals_share_a_node();
void test_get_min_and_max_covg_of_nodes_in_supernode();
void test_db_graph_supernode_for_specific_person_or_pop();
void test_db_graph_load_array_with_next_batch_of_nodes_corresponding_to_consecutive_bases_in_a_chrom_fasta();
void test_db_graph_make_reference_path_based_sv_calls();
void test_db_graph_make_reference_path_based_sv_calls_null_test_1();
void test_db_graph_make_reference_path_based_sv_calls_null_test_2();
void test_db_graph_make_reference_path_based_sv_calls_null_test_3();
void test_db_graph_make_reference_path_based_sv_calls_null_test_4();
void test_db_graph_make_reference_path_based_sv_calls_null_test_5();
void test_db_graph_make_reference_path_based_sv_calls_test_1();
void test_db_graph_make_reference_path_based_sv_calls_test_2();
void test_db_graph_make_reference_path_based_sv_calls_test_3();
void test_db_graph_make_reference_path_based_sv_calls_test_4();
void test_db_graph_make_reference_path_based_sv_calls_test_5();
void test_db_graph_make_reference_path_based_sv_calls_test_6();
void test_db_graph_make_reference_path_based_sv_calls_test_7();
void test_db_graph_make_reference_path_based_sv_calls_test_8();
void test_db_graph_make_reference_path_based_sv_calls_test_9();


