void test_parse_colourinfo_argument();
void test_get_numbers_from_comma_sep_list();
void test_parse_cmdline_inner_loop_are_basic_variables_correctly_set();
void test_parse_cmdline_inner_loop_are_basic_variables_correctly_set_2();

