void test_load_two_people_in_same_populations_and_print_separately_their_supernodes();
void test_take_four_people_each_with_one_read_and_find_variants();
void test_take_two_people_sharing_an_alu_and_find_supernodes();
